language: node_js
node_js: stable

# Travis-CI Caching	
cache:	
  directories:	
    - node_modules	

install:
  - sudo apt-get install git-ftp

before_script:  

script:
  - npm run build
  
after_script:
  - cd ./dist
# gh-pages deploy
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
# ftp deploy
  - git config git-ftp.url "ftp://120.25.86.111:23/vue-gathering"
  - git config git-ftp.user ${FTP_USERNAME}
  - git config git-ftp.password  ${FTP_PASSWORD}
  - git ftp init
  - git ftp push
# E: Build LifeCycle

branches:
  only:
    - master

# deploy:
#   skip_cleanup: true
#   provider: script
#   script: node deploy.js
#   on:
#     branch: master

env:
 global:
   - GH_REF: github.com/zhijunzhou/vue-gathering.git
   - GIT_FTP: github.com/git-ftp/git-ftp.git
